name: "Publish Docker Image & Deploy to AppRunner"
on:
  push:
    branches: [ feature/cicd ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Development
      url: https://wpswhvhexf.eu-west-1.awsapprunner.com
    steps:
      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_DEPLOY_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEPLOY_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEPLOY_REGION }}
      # Login to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      # Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v4
      # Create env file
      - name: Create .env file
        run: |
          touch .env
          echo NEXT_PUBLIC_AWS_GATEWAY_BASE_URL="${{ secrets.INFRA_API_BASE_URL }}" >> .env
          echo NEXT_PUBLIC_SUPABASE_URL="${{ secrets.SUPABASE_URL }}" >> .env
          echo NEXT_PUBLIC_SUPABASE_ANON_KEY="${{ secrets.SUPABASE_ANON_KEY }}" >> .env
          echo NEXT_PUBLIC_SERVER_HOST="${{ vars.SERVER_HOST }}" >> .env
          echo NEXT_PUBLIC_S3_STATIC_RESOURCES_BASE_URL="${{ vars.STATIC_RESOURCES_BASE_URL }}" >> .env
          echo NEXT_PUBLIC_PRIVACY_POLICY_URL="${{ vars.PRIVACY_POLICY_URL }}" >> .env
          echo NEXT_PUBLIC_TERMS_AND_CONDITIONS_URL="${{ vars.TERMS_AND_CONDITIONS_URL }}" >> .env
          echo NEXT_PUBLIC_GOOGLE_ANALYTICS_MEASUREMENT_ID="${{ vars.GOOGLE_ANALYTICS_MEASUREMENT_ID }}" >> .env
      # Publish docker image to ECR
      - name: Publish docker image to ECR
        run: make publish
      # Trigger manual deploy of AppRunner service
      - name: Trigger manual deploy of AppRunner service 
        env: 
          SERVICE_ARN: ${{ secrets.AWS_APPLICATION_SERVICE_ARN }}
        run: aws apprunner start-deployment --service-arn $SERVICE_ARN
